# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

services:
  - postgresql

#before_install:
#  - psql -c 'create database cinema;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - senebh@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

#env:
#  global:
#   CODECOV_TOKEN="59fad60d-ac7c-43f9-996a-eca6fd83bd6f"